// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"cloud.google.com/go/secretmanager/apiv1/secretmanagerpb"
	"github.com/googleapis/gax-go/v2"
	mock "github.com/stretchr/testify/mock"
)

// NewGoogleSecretsManagerAPI creates a new instance of GoogleSecretsManagerAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGoogleSecretsManagerAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *GoogleSecretsManagerAPI {
	mock := &GoogleSecretsManagerAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// GoogleSecretsManagerAPI is an autogenerated mock type for the SecretsManagerAPI type
type GoogleSecretsManagerAPI struct {
	mock.Mock
}

type GoogleSecretsManagerAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *GoogleSecretsManagerAPI) EXPECT() *GoogleSecretsManagerAPI_Expecter {
	return &GoogleSecretsManagerAPI_Expecter{mock: &_m.Mock}
}

// AccessSecretVersion provides a mock function for the type GoogleSecretsManagerAPI
func (_mock *GoogleSecretsManagerAPI) AccessSecretVersion(ctx context.Context, req *secretmanagerpb.AccessSecretVersionRequest, opts ...gax.CallOption) (*secretmanagerpb.AccessSecretVersionResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, req, opts)
	} else {
		tmpRet = _mock.Called(ctx, req)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for AccessSecretVersion")
	}

	var r0 *secretmanagerpb.AccessSecretVersionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *secretmanagerpb.AccessSecretVersionRequest, ...gax.CallOption) (*secretmanagerpb.AccessSecretVersionResponse, error)); ok {
		return returnFunc(ctx, req, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *secretmanagerpb.AccessSecretVersionRequest, ...gax.CallOption) *secretmanagerpb.AccessSecretVersionResponse); ok {
		r0 = returnFunc(ctx, req, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*secretmanagerpb.AccessSecretVersionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *secretmanagerpb.AccessSecretVersionRequest, ...gax.CallOption) error); ok {
		r1 = returnFunc(ctx, req, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GoogleSecretsManagerAPI_AccessSecretVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AccessSecretVersion'
type GoogleSecretsManagerAPI_AccessSecretVersion_Call struct {
	*mock.Call
}

// AccessSecretVersion is a helper method to define mock.On call
//   - ctx context.Context
//   - req *secretmanagerpb.AccessSecretVersionRequest
//   - opts ...gax.CallOption
func (_e *GoogleSecretsManagerAPI_Expecter) AccessSecretVersion(ctx any, req any, opts ...any) *GoogleSecretsManagerAPI_AccessSecretVersion_Call {
	return &GoogleSecretsManagerAPI_AccessSecretVersion_Call{Call: _e.mock.On("AccessSecretVersion",
		append([]any{ctx, req}, opts...)...)}
}

func (_c *GoogleSecretsManagerAPI_AccessSecretVersion_Call) Run(run func(ctx context.Context, req *secretmanagerpb.AccessSecretVersionRequest, opts ...gax.CallOption)) *GoogleSecretsManagerAPI_AccessSecretVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *secretmanagerpb.AccessSecretVersionRequest
		if args[1] != nil {
			arg1 = args[1].(*secretmanagerpb.AccessSecretVersionRequest)
		}
		var arg2 []gax.CallOption
		var variadicArgs []gax.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]gax.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *GoogleSecretsManagerAPI_AccessSecretVersion_Call) Return(accessSecretVersionResponse *secretmanagerpb.AccessSecretVersionResponse, err error) *GoogleSecretsManagerAPI_AccessSecretVersion_Call {
	_c.Call.Return(accessSecretVersionResponse, err)
	return _c
}

func (_c *GoogleSecretsManagerAPI_AccessSecretVersion_Call) RunAndReturn(run func(ctx context.Context, req *secretmanagerpb.AccessSecretVersionRequest, opts ...gax.CallOption) (*secretmanagerpb.AccessSecretVersionResponse, error)) *GoogleSecretsManagerAPI_AccessSecretVersion_Call {
	_c.Call.Return(run)
	return _c
}
