// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/secretsmanager"
	mock "github.com/stretchr/testify/mock"
)

// NewSecretsManagerAPI creates a new instance of SecretsManagerAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSecretsManagerAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *SecretsManagerAPI {
	mock := &SecretsManagerAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SecretsManagerAPI is an autogenerated mock type for the SecretsManagerAPI type
type SecretsManagerAPI struct {
	mock.Mock
}

type SecretsManagerAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *SecretsManagerAPI) EXPECT() *SecretsManagerAPI_Expecter {
	return &SecretsManagerAPI_Expecter{mock: &_m.Mock}
}

// GetSecretValue provides a mock function for the type SecretsManagerAPI
func (_mock *SecretsManagerAPI) GetSecretValue(context1 context.Context, getSecretValueInput *secretsmanager.GetSecretValueInput, fns ...func(*secretsmanager.Options)) (*secretsmanager.GetSecretValueOutput, error) {
	var tmpRet mock.Arguments
	if len(fns) > 0 {
		tmpRet = _mock.Called(context1, getSecretValueInput, fns)
	} else {
		tmpRet = _mock.Called(context1, getSecretValueInput)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetSecretValue")
	}

	var r0 *secretsmanager.GetSecretValueOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *secretsmanager.GetSecretValueInput, ...func(*secretsmanager.Options)) (*secretsmanager.GetSecretValueOutput, error)); ok {
		return returnFunc(context1, getSecretValueInput, fns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *secretsmanager.GetSecretValueInput, ...func(*secretsmanager.Options)) *secretsmanager.GetSecretValueOutput); ok {
		r0 = returnFunc(context1, getSecretValueInput, fns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*secretsmanager.GetSecretValueOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *secretsmanager.GetSecretValueInput, ...func(*secretsmanager.Options)) error); ok {
		r1 = returnFunc(context1, getSecretValueInput, fns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SecretsManagerAPI_GetSecretValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecretValue'
type SecretsManagerAPI_GetSecretValue_Call struct {
	*mock.Call
}

// GetSecretValue is a helper method to define mock.On call
//   - context1 context.Context
//   - getSecretValueInput *secretsmanager.GetSecretValueInput
//   - fns ...func(*secretsmanager.Options)
func (_e *SecretsManagerAPI_Expecter) GetSecretValue(context1 any, getSecretValueInput any, fns ...any) *SecretsManagerAPI_GetSecretValue_Call {
	return &SecretsManagerAPI_GetSecretValue_Call{Call: _e.mock.On("GetSecretValue",
		append([]any{context1, getSecretValueInput}, fns...)...)}
}

func (_c *SecretsManagerAPI_GetSecretValue_Call) Run(run func(context1 context.Context, getSecretValueInput *secretsmanager.GetSecretValueInput, fns ...func(*secretsmanager.Options))) *SecretsManagerAPI_GetSecretValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *secretsmanager.GetSecretValueInput
		if args[1] != nil {
			arg1 = args[1].(*secretsmanager.GetSecretValueInput)
		}
		var arg2 []func(*secretsmanager.Options)
		var variadicArgs []func(*secretsmanager.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*secretsmanager.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *SecretsManagerAPI_GetSecretValue_Call) Return(getSecretValueOutput *secretsmanager.GetSecretValueOutput, err error) *SecretsManagerAPI_GetSecretValue_Call {
	_c.Call.Return(getSecretValueOutput, err)
	return _c
}

func (_c *SecretsManagerAPI_GetSecretValue_Call) RunAndReturn(run func(context1 context.Context, getSecretValueInput *secretsmanager.GetSecretValueInput, fns ...func(*secretsmanager.Options)) (*secretsmanager.GetSecretValueOutput, error)) *SecretsManagerAPI_GetSecretValue_Call {
	_c.Call.Return(run)
	return _c
}
