// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/ssm"
	mock "github.com/stretchr/testify/mock"
)

// NewSSMAPI creates a new instance of SSMAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSSMAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *SSMAPI {
	mock := &SSMAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SSMAPI is an autogenerated mock type for the SSMAPI type
type SSMAPI struct {
	mock.Mock
}

type SSMAPI_Expecter struct {
	mock *mock.Mock
}

func (_m *SSMAPI) EXPECT() *SSMAPI_Expecter {
	return &SSMAPI_Expecter{mock: &_m.Mock}
}

// GetParameter provides a mock function for the type SSMAPI
func (_mock *SSMAPI) GetParameter(context1 context.Context, getParameterInput *ssm.GetParameterInput, fns ...func(*ssm.Options)) (*ssm.GetParameterOutput, error) {
	var tmpRet mock.Arguments
	if len(fns) > 0 {
		tmpRet = _mock.Called(context1, getParameterInput, fns)
	} else {
		tmpRet = _mock.Called(context1, getParameterInput)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetParameter")
	}

	var r0 *ssm.GetParameterOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ssm.GetParameterInput, ...func(*ssm.Options)) (*ssm.GetParameterOutput, error)); ok {
		return returnFunc(context1, getParameterInput, fns...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ssm.GetParameterInput, ...func(*ssm.Options)) *ssm.GetParameterOutput); ok {
		r0 = returnFunc(context1, getParameterInput, fns...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssm.GetParameterOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ssm.GetParameterInput, ...func(*ssm.Options)) error); ok {
		r1 = returnFunc(context1, getParameterInput, fns...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SSMAPI_GetParameter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParameter'
type SSMAPI_GetParameter_Call struct {
	*mock.Call
}

// GetParameter is a helper method to define mock.On call
//   - context1 context.Context
//   - getParameterInput *ssm.GetParameterInput
//   - fns ...func(*ssm.Options)
func (_e *SSMAPI_Expecter) GetParameter(context1 any, getParameterInput any, fns ...any) *SSMAPI_GetParameter_Call {
	return &SSMAPI_GetParameter_Call{Call: _e.mock.On("GetParameter",
		append([]any{context1, getParameterInput}, fns...)...)}
}

func (_c *SSMAPI_GetParameter_Call) Run(run func(context1 context.Context, getParameterInput *ssm.GetParameterInput, fns ...func(*ssm.Options))) *SSMAPI_GetParameter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ssm.GetParameterInput
		if args[1] != nil {
			arg1 = args[1].(*ssm.GetParameterInput)
		}
		var arg2 []func(*ssm.Options)
		var variadicArgs []func(*ssm.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*ssm.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *SSMAPI_GetParameter_Call) Return(getParameterOutput *ssm.GetParameterOutput, err error) *SSMAPI_GetParameter_Call {
	_c.Call.Return(getParameterOutput, err)
	return _c
}

func (_c *SSMAPI_GetParameter_Call) RunAndReturn(run func(context1 context.Context, getParameterInput *ssm.GetParameterInput, fns ...func(*ssm.Options)) (*ssm.GetParameterOutput, error)) *SSMAPI_GetParameter_Call {
	_c.Call.Return(run)
	return _c
}
